language: java

jdk:
- openjdk8
- openjdk11

env:
  global:
  - secure: fL0qXNsajD5uSC6ra+ltQdWG0fvWKhl2gJ9Ko2/3FzLRn6gBalNEWwt+sH2Ugup6FrD6+x1jkG9B/8YNMfToxQaCtAxmj0y5vGjYtX8Wkd8X8d0ne98YYBaphqpXmXn6whOcY6rVGtwuS/h74JFMuAEPH4YCEP5c0jwrMf77egFM+f2916hWxFNPtAY+GFkMHDee5FML7if8bWBKnZ0vrvgCBvAkIrDGia6pfC80c5iMgQldiAZpfUkAL5LHRKCeSnJjVO/F3ODoT4mjHzS4RJAZCwfqBnZRaSUoyy7UCm8epEx+8apnfo0N9am5jHqvR+CLJeSKFXikKrLMFKqlCsLsHY36/wuxqFb8Hj6+y3RCNo1QbLATnIcNbNYtgx5BXMSiNFw95CamBUHfLDMGexVZEoJXTblu808I9+q2jJPBZFq/3/JS6NinCRKZex22U8aE5fCuQlyvyk4KGOmsIriaDviJe0hhNTb7CHDBsG9eas8sN/HESGgfHXJtUDDtg9PdpQHv67x2tW6CbRPWoX4XOrRLFTI6eaec7PmcZcMLrLlB0QoyCjqVyJWaOe1tPavWbFzKC0Zy+BGkX6vW95tQCLRNKWIjP0orll/99kgULFU7BoRkSiwOncHeDzcdVAt4IuSe8/Lr3MFelatFQM1gSRVhvgKCYAdCB7YVEfM=
  - secure: iK1j7XsF7Am3wVF1iIy7zpQDZephjwKLwcCanwNurLFRBLRMLLLfKFZY4oSJa879IRxIQiGXFI7+XlWKLRhBDp2glAyyjYFkWOq+1/0/cMOahCq4VO/Nt6495SfvO9n12wQsHVtdfgQoJQcS7fHiu4vwFJ6FBR1irGq3v5PM5NLLEbh2xZpsFGOSe6j90O1rUENb49YnJIJH4j72dYNnUi+6X3D540XtePkwGckyXl6e2y2uOAh5gbbwM5RRwKft1418SvrwKeRQ2v1q8jjsrdAZ19CMFqdDovxR2sune/9JXqosn7mAEmbTbUsqsKYwofKXQR5vqZ0SGOZ0SYJWFm9jR79SwGiyTMjNXUuTvTyC8rmE0u7CmGtz5KamR7fSo6ISVBx1jV/T27syPYJrvTZH8gRZTkzR62pMIPFjpNspIf17bGakVTzqQhxTQQy2OORqvPz1YBOKVE+wVnqMC5i3OfuKj11gKSVJAe5TLumutS6yZepb9V5zR9zdinZpdlNXLKTJVZxuHTi+DIuWJ8+VzxiC2lL2wm8mnhR7YGMVVxcNU1L+O8bE1WxMrKSE3Zz9SUPKYTLTSW54E0GUqGddogWqkTeVgCkKRdgRzCsU9jPWLKAyyMDnPZWCGFET2LqWpgolf4UvmDQGqjeunHCPh7Mjwgd+qJB2piL3zI8=
  - secure: hus8CreqV8XhiBNq1XSCsnMhDgYgq2pNJWoC2p+dPjoN5+Sg/god27ZFT1+j15Rr+EhOQoX1KBTsbKzuNiVSLU/nqM/mXn+XtFsjbcu7itz/gz5dArI+BU8Eco70v/c8D3HOQY++84OwPlPS5ZzHiexTHJx/b4ePSVYwFDj6PcV5RKCO0g0yaJouhRKb8nRS4wqO+D7xk4j61SaeTkt/CB/da78Xyvrlxv2Sqxpb6/vQWKIr/43fYOT91kGkbKMM5f8iKFgFG/3Ebz2mygfhQuRqLmtrwh6RdKRs8fekWiaCHvj6w8cjbEBBtAiYEw+PdsbQ/mEBxTs1OBmT9LeENW8OQeOqtD0renBYREF2Y4CHMk6sR4U4uMHgG6WKDEBB3ehAXE3ZPwyKtIn5FwUv8lQKqY2APRktQJ98gF8y1wDGoz/hIooU38GcB0V9utc1vkYp9elEbP78v8XaB5SX4OYLvViqvqoD1+NOWt8A2e7nCBAo8kbmNg/I0M3bPBtEXtqP/m0/GwZrqu5ZnuQ6qcpgmk+nPkqeN7gpuqvZTp0a9OjfnWlrl5aAcsjZeAg9X1YmMGCi/evz1j184UfaZ09ScZtBxNKLW6frHXY7yvShh+wT+jfrCnmLaADE1pnSxcgClljSd2U4qDABMdbUUTpu+4bwXcA3bN2Pn+PZphY=
  - secure: rNCcaYwEWcPs/y/xPCS/0caWXT7vdNbKVioF85lrGFgHay2BDNjxzxxEHTBLjQ8ZRPNZFbvhn9QM09b9/q4INrqUNXt/Z+ptMxRPizYQpp+u2t7uRY9ZoKsYW27JTiU3h9xfdhG22lnihcSYdJ4Ba3cgPCesgY1iV6XjXXAIDobI8tJ7pyQkCaiVgbkTjj2/WH8bLCie4yOhVHHPMDqtH3NC6W1mdV3iHI19T/uu72d2dAIVyc9/C5k7c9orqEK6wN3uUHoleXYwqfVb/19d0+/HmPWXvKryGdKI6kFu2YHaLoms+q+p0oF8PVKe2DNCgOPEMuNDzIvFbHtkFMPpLRJd3ScNTLsrodj58/iKwm0RLl9q7He/YUffetBDQ3H1mEDIHpHiDL8/IUSPFtlsEiwrkonCsCQS73cYJqGrKsV7//aXsJKrs6FocJ5Efzpo+TkCtVWHfni4j4B5k7D+5TSB4nwkv8SZ7aWsXdxrdbJArNYuYmqicnae1niVzipmYu1nbWziBrqD4f/5ouhHv/fg3OeG4ByJBeQ8B5or69ZlRil5TmvvFZdXrollF2RbbDCknfL970a1eEaTFVU+iW3gIApjlVtSK4mFJKI0bdmPQ4kneBGR0Pi59lQeJ8Arp8hHE8BEnPsD6KhTHPCeEA/9do8DaxUwhpUMCnCtc5w=

before_install:
- openssl aes-256-cbc -K $encrypted_ae11b2b1856c_key -iv $encrypted_ae11b2b1856c_iv
  -in secring.gpg.enc -out secring.gpg -d

install:
- "./gradlew clean"
- "./gradlew assemble"
- "./gradlew flashlibFrcAll"

script:
- "./gradlew check"

before_deploy:
- git config --local user.name "Travis CI"
- git config --local user.name "build@travis-ci.com"

deploy:
- provider: script
  script: "./gradlew publish -PSIGN_PUBLISH=true -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE}
    -Psigning.secretKeyRingFile=secring.gpg"
  skip_cleanup: true
  on:
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(-.*)?"
    branch: master
    tags: true
- provider: releases
  api_key:
    secure: YwlyQmXs530zK+1kNHaUus1uPfJkUtDpPlHSQMdzF4vB0gB6nzZc4XyLTH/H8STQbB93Xfwd17Y6YV9VIe9P9/yp22qaz8pMxs5/5TGhsirLw6ZdWS2zDdVaK5c8pddxk54mgIZdBT3TYvDoSvzmdgLH3T53u64FWSNykbVTEsgp0S7FfegGYucR9/lLJ8dqBoS89+9aMX1hB2Y8H2uSj7hPjcdatmFFusbAejH2hkrxalziGUULaZq/La8XSb0kbd9sAqG6bW7D/MvLwWdZm/VHBav51oQp61/nvnYz97EeuZunuxK2bz278jicpGAJGonIRC+48sa/s8Xtr1KzxZdj4Lw3es+Ldx4EaBtLHa5wpPBZQHwCg+tujyuxklKU5it9jkYmy7MWnLryGXroy0ORhIVvhOZRzL+G7EjfuN8ipxVc08dzyz2/7uD2ar+SYBplgD5OHcbQUzML1QGev0eniMpGlVQK3o+TGVXWuLfmKJqZMbIfhS4z7rCtgHPcqVicE8/tb3oLaK0kZKu9qqbeShtKJKxjP0y1jocPQChxsu4FegnrnPQquu+6OtpXg/njzNcQQhp7phTU5yUnAsyIOCRlGR/LrEwDEewKn+z7bIuJSHAX39RbEX/wEr6B0BgfHpIYY+iw8UTa0kTEb6o0nKruCoumSqsU6uSfyxs=
  file:
  - build/flashlib-frc-all.jar
  - README.md
  skip_cleanup: true
  draft: true
  on:
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(-.*)?"
    repo: Flash3388/FlashFRC
    branch: master
    tags: true
